name: Terraform workflow

on:
  push:
    branches:
      - main
      
permissions:
      id-token: write
      contents: read

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-code
        uses: actions/checkout@v2

      - name: Az login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az account show
            az group list

        
      - name: Set up terraform
        uses:  hashicorp/setup-terraform@v2.0.2
        
      
      - name: Terraform Apply
        run: |
              echo "**terraform init"
              terraform init 
               
               echo "** terraform apply"
              terraform apply -auto-approve -var JWT_SECRET="${{secrets.TF_JWT_SECRET}}" 
              -var MONGO_URI="${{secrets.TF_MONGO_URI}}"
              -var secret= "${{secrets.TF.SECRET}}"
              -var app_version= "${{secrets.TF_APP_VERSION}}"
              -var client_id = "${{secrets.TF_CLIENT_ID}}"
              -var client_secret = "${{secrets.TF_CLIENT_SECRET}}"
        working-directory: ./terraform
      - name: Terraform Apply
        run: |
              echo "**terraform DESTROY"
              terraform apply -auto-approve -var JWT_SECRET="${{secrets.TF_JWT_SECRET}}" 
              -var MONGO_URI="${{secrets.TF_MONGO_URI}}"
              -var secret= "${{secrets.TF.SECRET}}"
              -var app_version= "${{secrets.TF_APP_VERSION}}"
              -var client_id = "${{secrets.TF_CLIENT_ID}}"
              -var client_secret = "${{secrets.TF_CLIENT_SECRET}}"
        working-directory: ./terraform
